# Site settings
title: "My Awesome Site"
description: "A description of your site"
url: "https://koykoy200078.github.io/portfolio"
baseurl: "" # Leave this empty to serve from the root

# Build settings
markdown: kramdown
theme: minima

# Optional settings
# Uncomment and customize as needed
# author: "Your Name"
# email: "your-email@example.com"
# twitter_username: "your-twitter-handle"
# github_username: "your-github-username"
